online_catalog/employees/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter
from .views import EmployeesListSet, EmployeesViewSet



router = DefaultRouter()
router.register('employees', EmployeesViewSet, basename='one')
urlpatterns = [
    path('search_employee/', EmployeesViewSet.search_employee , name='search_employee'),
    path('', EmployeesListSet.as_view(), name='index'),
    path('<int:pk>/', EmployeesViewSet.employee_view, name='employee'),
    path('<int:pk>/edit/', EmployeesViewSet.employee_edit, name='employee_edit')
]

online_catalog/online_catalog/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
    path('', include('employees.urls')),

]

if settings.DEBUG:
    
    #urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),) 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

online_catalog/users/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("signup/", views.SignUp.as_view(), name="signup")

]

online_catalog/employees/models.py
from django.db import models


class Employee(models.Model):
    first_name = models.CharField(verbose_name="Имя", max_length=100)
    last_name = models.CharField(verbose_name="Фамилия", max_length=100)
    patronymic = models.CharField(verbose_name="Отчество", max_length=100)
    image = models.ImageField(verbose_name="Фото работника", upload_to="employees/",
                              blank=True, null=True)
    title = models.CharField(verbose_name="Должность", max_length=100)
    hired_date = models.DateField(verbose_name="Дата приема на работу", blank=True, null=True)
    salary = models.IntegerField(verbose_name="Размер заработной платы", blank=True, null=True)
    parent = models.ForeignKey('self', verbose_name='Начальник', on_delete=models.SET_NULL, blank=True, null=True)

online_catalog/employees/forms.py
from django import forms

from .models import Employee

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ('first_name', 'last_name', 'patronymic', 'image', 'title', 'hired_date', 'salary', 'parent')
        label_name = {
            'first_name': 'Имя',
            'last_name' : 'Фамилия',
            'patronymic' : 'Отчество', 
            'image' : 'Фотография',
            'title' : 'Должность',
            'hired_date' : 'Дата наима',
            'salary' : 'Зарплата',
            'parent' : 'Начальник',
        }
        help_texts = {
            'first_name': 'Имя сотрудника',
            'last_name' : 'Фамилия сотрудника',
            'patronymic' : 'Отчество сотрудника',
            'image' : 'Фотография сотрудника',
            'title' : 'Должность сотрудника',
            'hired_date' : 'Дата наима сотрудника',
            'salary' : 'Зарплата сотрудника',
            'parent' : 'Начальник сотрудника',
        }


class SearchForm(forms.Form):
    query = forms.CharField(label='Поиск')

online_catalog/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("first_name", "last_name", "username", "email")

online_catalog/employees/views.py
from django.shortcuts import render, redirect
from rest_framework import filters, status, viewsets
from rest_framework.response import Response
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404
from django.views import generic
# from haystack.query import SearchQuerySet
from rest_framework.pagination import PageNumberPagination
from django.db.models import Q

from online_catalog.settings import PAGE_SET_10
from .models import Employee
from .serializer import GetEmployeeSerializer
from .forms import EmployeeForm, SearchForm


class EmployeesListSet(generic.ListView):
    model = Employee
    

class EmployeesViewSet(viewsets.ModelViewSet):
    queryset = Employee.objects.all()

    # def all_emloyees(request):
    #     emloyees = Employee.objects.all()
    #     paginator = Paginator(emloyees, PAGE_SET_10)
    #     page_number = request.GET.get("page")
    #     page = paginator.get_page(page_number)
    #     context = {
    #         "page": page,
    #         "paginator": paginator
    #     }
    #     return render(
    #         request,
    #         "all_employees.html",
    #         context
    #     )

    def search_employee(request):
        form = SearchForm()
        cd = []
        results = []
        if 'query' in request.GET:
            form = SearchForm(request.GET)
            if form.is_valid():
                cd = form.cleaned_data
                results = Employee.objects.all().filter((Q(title__icontains=cd['query']) | Q(first_name__icontains=cd['query'])) | 
                                                        (Q(last_name__icontains=cd['query']) | Q(patronymic__icontains=cd['query']))
                                                        )
            cd = cd['query']

        paginator = Paginator(results, PAGE_SET_10)
        page_number = request.GET.get("page")
        page = paginator.get_page(page_number)
        context = {
            "page": page,
            "paginator": paginator,
            'form': form,
            'cd': cd,
        }
        return render(request,
                    'search_employee.html',
                    context)


    def employee_view(request, pk):
        employee = get_object_or_404(Employee, pk=pk)
        context = {
            'employee': employee
        }
        return render(request, 'employee.html', context)

    def employee_edit(request, pk):
        employee = get_object_or_404(Employee, pk=pk)
        form = EmployeeForm(request.POST or None, files=request.FILES or None,
                    instance=employee)

        if not form.is_valid():
            return render(request, "employee_edit.html", {"form": form, "employee": employee, })

        form.save()
        return redirect('employee', pk=pk)

online_catalog/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy("index")
    template_name = "signup.html"

online_catalog/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
  <main role="main" class="container">
      <div class="row">
          <!-- Левый вспомогательный блок -->
          <div class="col-md-3 mb-3 mt-1">
              <div class="card">
                  <div class="card-body">
                      <ul class="list-group list-group-flush">
                          <li class="list-group-item">
                              <div class="h3">
                                  Об авторе
                              </div> 
                          </li>
                          <li class="list-group-item">
                              <div class="h6 text-muted">
                                  Полезный короткий текст
                              </div>
                          </li>
                      </ul>                                               
                  </div>                    
              </div>                
          </div>
          <!-- Тело страницы -->
          <div class="col-md-9">
              <div class="card-body">                    
                  <div class="card-text">
                      <p>Текст страницы "Об авторе"</p>
                  </div>                    
              </div>                
          </div>            
      </div>        
  </main>
{% endblock %}

online_catalog/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Об технологиях проекта{% endblock %}
{% block content %}
  <main role="main" class="container">
      <div class="row">
          <!-- Левый вспомогательный блок -->
          <div class="col-md-3 mb-3 mt-1">
              <div class="card">
                  <div class="card-body">
                      <ul class="list-group list-group-flush">
                          <li class="list-group-item">
                              <div class="h3">
                                  Об технологиях
                              </div> 
                          </li>
                          <li class="list-group-item">
                              <div class="h6 text-muted">
                                  Полезный короткий текст
                              </div>
                          </li>
                      </ul>                                               
                  </div>                    
              </div>                
          </div>
          <!-- Тело страницы -->
          <div class="col-md-9">
              <div class="card-body">                    
                  <div class="card-text">
                      <p>Текст страницы "Об технологиях"</p>
                  </div>                    
              </div>                
          </div>            
      </div>        
  </main>
{% endblock %}

online_catalog/templates/base.html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Online catalog of employees{% endblock %}</title>
    <!-- Загрузка статики -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
</head>

<body>
    {% include "nav.html"%}
    <main>
        <div class="container">
            <h1>{% block header %}Online catalog of employees{% endblock %}</h1>
            {% block content %}
            <!-- Содержимое страницы -->
            {% endblock %}
        </div>
    </main>
    {% include "footer.html"%}

</body>

</html>

online_catalog/templates/employee.html
{% extends "base.html" %} 
{% block title %}Employees{% endblock %}
{% block header %}Cотрудник{% endblock %}
{% load cache %}

{% block content %}
<p>
<div class="card mb-3 mt-1 shadow-sm">
<div class="d-flex justify-content-between align-items-center">
    {% load thumbnail %}
    {% thumbnail employee.image "300x350" crop="center" upscale=True as im %}
        <img src="{{ im.url }}" />
    {% endthumbnail %}
    
    <div class="card-body">
        <h3><strong class="d-block text-gray-dark">{{ employee.first_name }}  {{ employee.last_name }}  {{ employee.patronymic }}</strong></h3>
        <p><strong class="d-block text-gray-dark">Должность:  {{ employee.title }}</strong></p>    
            <p>Зарплата: {{employee.salary}}р.</p>
            <p>Дата наима: {{employee.hired_date}}</p>
    </div> 
</div>
    {% if user.is_authenticated %}
        <a class="btn btn-sm btn-info" href="{% url 'employee_edit' employee.pk %}" role="button">
            Редактировать
        </a>
    {% endif %}
</div>
</p>

{% endblock %}

online_catalog/templates/employee_edit.html
{% extends "base.html" %}
{% load user_filters %}
{% load thumbnail %}
{% block title %}
Редактирование записи
{% endblock %}
{% block header %}
        Редактирование записи
{% endblock %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">
            Редактирование записи
            </div>
            <div class="card-body">

                {% for error in form.errors %}
                  <div class="alert alert-danger" role="alert">
                      {{ error|escape }}
                  </div>
                {% endfor %}

            <form action=
                    "{% url 'employee_edit' employee.id %}"
             method="post" enctype="multipart/form-data">               
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group row" aria-required={% if field.field.required %} "true" {% else %} "false" {% endif %}>
                                <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                                <div class="col-md-6">
                                    {{ field|addclass:"form-control" }}
                                    {% if field.help_text %}
                                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                    {% endif %}
                                </div>                
                        </div>
                    {% endfor %}
                    <div class="col-md-6 offset-md-4">
                        <button type="submit" class="btn btn-primary">
                                Сохранить
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %} 

online_catalog/templates/employees/child.html
<ul>
    {% for subemployee in employee_list %}
        {% if employee == subemployee.parent %}
        <li>
            {% load thumbnail %}
            {% thumbnail subemployee.image "40x40" crop="center" upscale=True as im %}
              <img src="{{ im.url }}" />
            {% endthumbnail %}
            {{ subemployee.title }} <a class="card-link muted" href="{% url 'employee' subemployee.pk %}">({{subemployee.last_name}} {{subemployee.first_name}})</a>
            {% include "employees/child.html" with employee=subemployee employee_list=employee_list %}
        </li>
        {%endif%}
    {%endfor%}
</ul>

online_catalog/templates/employees/employee_list.html
{% extends "base.html" %} 
{% block title %}Online catalog of employees{% endblock %}
{% block header %}Онлайн каталог сотрудников{% endblock %}
{% load cache %}


{% block content %}
<div class="card mb-3 mt-1 shadow-sm">
  <p>
    {% if employee_list %}
    <ul>
      
      {% for employee in employee_list %}
        {% if employee.parent == None %}
        <li>
            {% load thumbnail %}
            {% thumbnail employee.image "40x40" crop="center" upscale=True as im %}
              <img src="{{ im.url }}" />
            {% endthumbnail %}      
            {{ employee.title }} <a class="card-link muted" href="{% url 'employee' employee.pk %}">({{employee.last_name}} {{employee.first_name}})</a>
            {% include "employees/child.html" with employee=employee employee_list=employee_list %}
        </li>
        {% endif %}
      {% endfor %}

    </ul>
    {% else %}
      <p>Нет сотрудников</p>
    {% endif %}
  </p>
  </div>
{% endblock %}

online_catalog/templates/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    
<p class="m-0 text-dark text-center ">ONLINE CATALOG</p>
</footer> 

online_catalog/templates/index.html
{% extends "base.html" %} 
{% block title %}Online catalog of employees{% endblock %}
{% block header %}Online catalog of employees{% endblock %}
{% load cache %}


{% block content %}
<div class="container">
    <div class="container">
        <!-- Вывод ленты записей -->
        {% cache 20 index_page %}
        {% for employee in page %}
            {% if employee.parent == None %}
                <div class="card-body">
                    <p class="card-text">
            {% endif %}
            
        {% endfor %}
    {% endcache %} 
    </div>
    {% if page.has_other_pages %}
        {% include "paginator.html" with items=page paginator=paginator%}
    {% endif %}
</div>
    
{% endblock %}

online_catalog/templates/nav.html
<nav class="navbar navbar-light" style="background-color: #dee3e8;">
    <a class="navbar-brand" href="{% url 'index' %}">Каталог</a>
    <a class="navbar-brand" href="{% url 'search_employee' %}">Весь список</a>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
            Пользователь: {{ user.username }}.
            <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
            <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
        {% else %}
            <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
            <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
        {% endif %}
    </nav>
</nav>

online_catalog/templates/paginator.html
{% if page.has_other_pages %}
<nav>
  <ul class="pagination">
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">&laquo; Предыдущая</span>
    </li>
    {% endif %}
    {% for i in page.paginator.page_range %}
    {% if page.number == i %}
    <li class="page-item active">
      <span class="page-link">{{ i }}
        <span class="sr-only">(текущая)</span>
      </span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">Следующая &raquo;</span>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

online_catalog/templates/profile.html
{% extends "base.html" %}
{% block title %}Последние обновления у пользователя{% endblock %}
{% block header %}Последние обновления у пользователя{% endblock %}
{% block content %}
<div class="row">
    <div class="card">
        <div class="card-body">
            <div class="h2">
                {{ user.get_full_name }}
            </div>
            <div class="h3 text-muted">
                {{ user.username }}
            </div>
        </div>
        </div>
</div>
{% endblock %}

online_catalog/templates/search_employee.html
{% extends "base.html" %} 
{% block title %}Online catalog of employees{% endblock %}
{% block header %}Все сотрудники{% endblock %}
{% load cache %}

{% block content %}
    {% if "query" in request.GET %}
        <h1>Сотрудники содержащие "{{ cd }}"</h1>
        {% for employee in page %}
        {% load thumbnail %}
        {% thumbnail employee.image "40x40" crop="center" upscale=True as im %}
          <img src="{{ im.url }}" />
        {% endthumbnail %}      
        {{ employee.title }} <a class="card-link muted" href="{% url 'employee' employee.pk %}">({{employee.last_name}} {{employee.first_name}})</a>
        {% include "employees/child.html" with employee=employee employee_list=employee_list %}
            {% empty %}
            <p>Нет результатов по вашему запросу.</p>
        {% endfor %}
        <p><a href="{% url 'search_employee' %}">Искать еще раз</a></p>
    {% else %}
        <h1>Поиск сотрудника</h1>
        <form action="." method="get">
            {{ form.as_p }}
            <input type="submit" value="Искать">
        </form>
    {% endif %}
    <!-- Вывод паджинатора -->
    {% if page.has_other_pages %}
        {% include "paginator.html" with items=page paginator=paginator%}
    {% endif %}
{% endblock %}

online_catalog/users/templates/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
{# загружаем фильтр #}
{% load user_filters %}

<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">Зарегистрироваться</div>
            <div class="card-body">
                
              {% for error in form.errors %}
                  <div class="alert alert-danger" role="alert">
                      {{ error|escape }}
                  </div>
                {% endfor %}

                <form method="post" action="{% url 'signup' %}">
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group row" aria-required={% if field.field.required %} "true" {% else %} "false" {% endif %}>
                                <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                                <div class="col-md-6">

                                    {{ field|addclass:"form-control" }}

                                    {% if field.help_text %}
                                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                    {% endif %}
                                </div>                
                        </div>
                    {% endfor %}

                    <div class="col-md-6 offset-md-4">              
                            <button type="submit" class="btn btn-primary">
                                Зарегистрироваться
                            </button>
                    </div>
                </form>
            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->

{% endblock %}